### PR TITLE
Add check_sigs functionality

### PR DESCRIPTION
**Pull request by zariye**
This PR adds `gpg --check-sigs` to the api.

### CODE REVIEW

**Comment by meskio** [comment]
This pull-req is including the commits from #149. To make the life of the maintainers easier will be nice or remove the commit of #149 from here or closing #149.

**Comment by zaraG** [comment]
Always the same mistake. :)
Done.

**Comment by zaraG** [comment]
@drebs and this the other one. :)

**Comment by drebs** [comment]
Hi, there is some ongoing process for making it feasible to get code merged into this repo, I will let you know as soon as there's some development on that. :-)

**Comment by meskio** [comment]
Me and @drebs have reviewed this pull-req and looks good.

**Comment by isislovecruft** [comment]
Hi, sorry, I've not had time for maintaining this lately. :(

@meskio, @drebs, @elijh, and @kalikaneko all should have push access to this repo, fwiw. I can also transfer it, and/or add more collaborators, if that helps.

**Comment by isislovecruft** [comment]
Merged for 2.1.0. Thanks very much, @zariye! And I'm very sorry again for the delay.

**Pull request merged**
