### PR TITLE
Handle KEY_CONSIDERED status lines

### PR DESCRIPTION
**Pull request by lynncyrin**
? closes https://github.com/isislovecruft/python-gnupg/issues/157

Branched off from https://github.com/isislovecruft/python-gnupg/pull/163 since that PR is stale

Also I incorporated this comment https://github.com/isislovecruft/python-gnupg/pull/163#issuecomment-268374944, hopefully the way you were thinking @isislovecruft

(I didn't see a contributing guide in this repo? So apologies if I did anything rude!)

### CODE REVIEW

**Comment by pelson** [comment]
This fixes the linked issue for me. (OSX, gpg (GnuPG) 2.1.21, libgcrypt 1.7.7).

**Comment by pelson** [comment]
Incidentally, the change that happened in Vinay's version: https://bitbucket.org/vinay.sajip/python-gnupg/commits/20b529201212

**Comment by glebpom** [comment]
Hi! Is it going to be merged? The issue is pretty major

**Comment by isislovecruft** [comment]
Hi @lynncyrin! Thanks for the PR! I've merged this into the `develop` branch and I'll release them as version 2.3.1.

**Pull request merged**
